### ISSUE TITLE
When logging in with Strava it gives error message

### ISSUE THREAD

**Issue by thwit** [c-harding/heatmapper#52]
I get error message:
'This token is not recognised. Perhaps it has expired, or already been used. '

When trying to log in with Strava. I have tried to clear cache, tried both Chrome and Firefox.

**Comment by c-harding** [comment]
Hi @witting97, thanks for creating the issue. I’ve deployed an old working version now (`calendar` branch), and I‘ll keep this issue open while the broken version (`gear` branch) has not been fixed.

**Comment by c-harding** [comment]
Fixed through #53
